# Generated by Django 4.2.5 on 2023-10-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наименование категории',
                'verbose_name_plural': 'наименования категорий',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_product/', verbose_name='изображение')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='цена покупки')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_last_modification', models.DateField(auto_now=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'наименование продукта',
                'verbose_name_plural': 'наименования продуктов',
                'ordering': ('name',),
            },
        ),
    ]
