# Generated by Django 4.2.1 on 2023-10-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150, verbose_name='наименование')),
                ('description_category', models.TextField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('name_category',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='наименование')),
                ('description_product', models.TextField(max_length=1000, verbose_name='описание')),
                ('image_product', models.ImageField(upload_to='image_product/', verbose_name='изображение')),
                ('category_product', models.CharField(max_length=150, verbose_name='категория')),
                ('purchase_price_product', models.CharField(max_length=150, verbose_name='цена покупки')),
                ('date_creation_product', models.CharField(max_length=150, verbose_name='дата создания')),
                ('date_last_modification_product', models.CharField(max_length=150, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('name_product',),
            },
        ),
    ]
